name: flutter_proyecto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0  # ✅ Debe estar fuera de 'flutter'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0  # ✅ Gráficos compatibles
  firebase_core: ^2.30.0         # Inicialización de Firebase
  firebase_auth: ^4.17.0         # Autenticación de usuarios
  cloud_firestore: 4.17.5
  flutter_application_1: ^0.0.2
  path_provider: ^2.1.5
  pdf: ^3.10.6
  printing: ^5.12.0
  file_picker: ^6.1.1
  intl: ^0.20.2
  downloads_path_provider_28: ^1.0.5
  permission_handler: ^11.3.1
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true



  # assets:
  #   - images/