// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDzyrGhA5k1Ub_zKTgFL8kJRjQBc0mWs28",
    appId: '1:602830887344:web:15ea55684847f335f59e75',
    messagingSenderId: '602830887344',
    projectId: 'ferreteriaplusone',
    authDomain: 'ferreteriaplusone.firebaseapp.com',
    databaseURL: 'https://ferreteriaplusone-default-rtdb.firebaseio.com',
    storageBucket: 'ferreteriaplusone.firebasestorage.app',
    measurementId: 'G-7M3HNXRWSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMjtOGWz9Er10e8lNYMiMd2Xu3C6Gjm8',
    appId: '1:602830887344:android:ea82c84e42c7fc4bf59e75',
    messagingSenderId: '602830887344',
    projectId: 'ferreteriaplusone',
    databaseURL: 'https://ferreteriaplusone-default-rtdb.firebaseio.com',
    storageBucket: 'ferreteriaplusone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmu_0XbUOqSg1jnk2edKSfgq5ObfLiOSI',
    appId: '1:602830887344:ios:89c82c4f759329aaf59e75',
    messagingSenderId: '602830887344',
    projectId: 'ferreteriaplusone',
    databaseURL: 'https://ferreteriaplusone-default-rtdb.firebaseio.com',
    storageBucket: 'ferreteriaplusone.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmu_0XbUOqSg1jnk2edKSfgq5ObfLiOSI',
    appId: '1:602830887344:ios:89c82c4f759329aaf59e75',
    messagingSenderId: '602830887344',
    projectId: 'ferreteriaplusone',
    databaseURL: 'https://ferreteriaplusone-default-rtdb.firebaseio.com',
    storageBucket: 'ferreteriaplusone.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzyrGhA5k1Ub_zKTgFL8kJRjQBc0mWs28',
    appId: '1:602830887344:web:56f61569679c4835f59e75',
    messagingSenderId: '602830887344',
    projectId: 'ferreteriaplusone',
    authDomain: 'ferreteriaplusone.firebaseapp.com',
    databaseURL: 'https://ferreteriaplusone-default-rtdb.firebaseio.com',
    storageBucket: 'ferreteriaplusone.firebasestorage.app',
    measurementId: 'G-4L9MXB6XWJ',
  );

}